Fix the failing `worker_wrapper` and tests by `requests==2.32.0`
The CI tests returned error messages like:
> Exception: Processing did no finish, did the worker hang ?

This was cause because the `worker_wrapper` gets on start:
> docker.errors.DockerException: Error while fetching server API version: Not supported URL scheme http+docker

NOTE since we are using multi-stage builds in docker, the `requests`
dependency was forced on the previous layer than the `worker_wrapper`
itself.